import Wordmark from "./Wordmark";

export default function Footer() {
  return (
    <>
      <section className={"footer section"}><div className={"w-layout-blockcontainer footer-container w-container"}><div className={"footer-row"}><div className={"footer-top-content-wrap"}><div className={"footer-top-left-content"}><div className={"footer-left-fast-content"}><a href={"/"} aria-current={"page"} className={"footer-logo-link w-nav-brand w--current"}><Wordmark /></a></div><div className={"footer-left-second-content"}><div className={"footer-left-second-text"}>© 2026, Omnidot.<br /></div><div className={"footer-left-second-text-02"}>All Rights Reserved.</div></div></div><div className={"footer-top-right-content"}><div className={"footer-right-text-wrap"}><div className={"footer-right-fast-text"}><div className={"footer-right-t"}>Address</div><div className={"footer-right-t-2"}>Omnidot Studio, opposite Tilley Gado House, MTN Office, Jos, Plateau State</div></div><div className={"footer-right-second-text"}><div className={"footer-text"}>Newsletter</div><div className={"form-block w-form"}><form id={"email-form-2"} name={"email-form-2"} data-name={"Email Form 2"} method={"get"} className={"form-two"} data-turnstile-sitekey={"0x4AAAAAAAQTptj2So4dx43e"}><input className={"text-input w-input"} maxLength={256} name={"email-2"} data-name={"Email 2"} placeholder={"Email Address"} type={"email"} id={"email-2"} required={true} /><input type={"submit"} data-wait={"Please wait..."} className={"footer-button-wrap w-button"} value={"Submit"} /></form><div className={"success-message-2 w-form-done"}><div>Thank you! Your submission has been received!</div></div><div className={"error-message w-form-fail"}><div>Oops! Something went wrong while submitting the form.</div></div></div></div></div></div></div><div className={"footer-bottom-content-wrap"}><div className={"footer-bottom-text"}><h1 className={"footer-header"}>omnidot©</h1></div></div><div className={"footer-img-wrap"}><img loading={"lazy"} src="/assets/6a5e950d52478c467739fe0c_Layer.avif" alt={"Close-up aerial view of a volcanic crater with a dark, textured interior and ridged edges."} className={"footer-top-img"} /></div><div className={"footer-shap-img-wrap"}><img loading={"lazy"} src="/assets/6a5e950d52478c467739fe0d_Footer-Shap-bg.avif" alt={"Dark green diffuse background with a subtle glowing oval shape in the center."} className={"footer-shap-img"} /></div></div><div className={"footer-bottom-shap-img"}><img loading={"lazy"} src="/assets/6a5e950d52478c467739fe17_Footer-Bottom-Shap.avif" alt={"Abstract symmetrical shape with green and orange gradient on a black background."} className={"footer-shap-bottom"} /></div></div></section>
    </>
  );
}
