import Wordmark from "./Wordmark";

export default function Header() {
  return (
    <>
      <section className={"header section-2"}><div className={"w-layout-blockcontainer header-container w-container"}><div className={"header-row"}><div className={"header-logo-wrap"}><div data-animation={"default"} data-collapse={"all"} data-duration={"400"} data-easing={"ease"} data-easing2={"ease"} role={"banner"} className={"header-wrapper w-nav"}><a href={"/"} aria-current={"page"} className={"header-logo-link w-nav-brand w--current"}><Wordmark /></a></div><div data-animation={"default"} data-collapse={"all"} data-duration={"400"} data-easing={"ease"} data-easing2={"ease"} role={"banner"} className={"header-wrapper w-nav"}><a href={"/"} aria-current={"page"} className={"header-logo-link w-nav-brand w--current"}><Wordmark /></a></div></div><div className={"heading-menu-wrap"}><div className={"heading-menu-box"}><a href={"#"} className={"header-menu-link w-inline-block"}><img loading={"lazy"} src="/assets/6a5e950d52478c467739fde1_Frame.png" alt={"Blue plus sign icon on transparent background."} className={"heading-menu-img"} /><div className={"heading-text"}>Menu</div></a></div><div className={"header-menu-wrap"}><div className={"header-menu-item-wrapper"}><div className={"header-menu-img-wrap"}><a href={"/"} aria-current={"page"} className={"header-logo-link w-nav-brand w--current"}><Wordmark /></a></div><div className={"header-menu-text-wrap"}><div className={"heading-menu-item-wrap"}><a href={"/"} aria-current={"page"} className={"menu-link w--current"}>Hero</a></div><div className={"heading-menu-item-wrap"}><a href={"#about"} className={"menu-link"}>About</a></div><div className={"heading-menu-item-wrap"}><a href={"#service"} className={"menu-link"}>Services</a></div><div className={"heading-menu-item-wrap"}><a href={"#project"} className={"menu-link"}>Project</a></div><div className={"heading-menu-item-wrap"}><a href={"#team"} className={"menu-link"}>Team</a></div><div className={"heading-menu-item-wrap"}><a href={"#testimonial"} className={"menu-link"}>Testimonials</a></div><div className={"heading-menu-item-wrap"}><a href={"#Comment"} className={"menu-link"}>Contact</a></div></div></div></div></div><div className={"heading-right-content-wrap"}><div className={"heading-right-fast-content"}><p className={"heading-right-p"}>Free 30-minute strategy call. No obligations.</p></div><div className={"heading-right-second-content"}><img loading={"lazy"} src="/assets/6a5f24b5fc772ee17a58430d_PASSPORT.png" alt={""} className={"heading-right-img"} /><a href={"tel:+2348134408179"} className={"header-call-link w-inline-block"}><div className={"heading-right-phone-call"}><img loading={"lazy"} src="/assets/6a5e950d52478c467739fde3_Right-Phone.png" alt={"Icon of a stylized smartphone with a curved screen on the right side."} className={"right-phone"} /></div></a></div></div></div></div></section>
    </>
  );
}
