import Wordmark from "./Wordmark";

export default function Header() {
  return (
    <>
      <section className={"header section-2"}><div className={"w-layout-blockcontainer header-container w-container"}><div className={"header-row"}><div className={"header-logo-wrap"}><div data-animation={"default"} data-collapse={"all"} data-duration={"400"} data-easing={"ease"} data-easing2={"ease"} role={"banner"} className={"header-wrapper w-nav"}><a href={"/"} aria-current={"page"} className={"header-logo-link w-nav-brand w--current"}><Wordmark /></a></div><div data-animation={"default"} data-collapse={"all"} data-duration={"400"} data-easing={"ease"} data-easing2={"ease"} role={"banner"} className={"header-wrapper w-nav"}><a href={"/"} aria-current={"page"} className={"header-logo-link w-nav-brand w--current"}><Wordmark /></a></div></div><div className={"heading-menu-wrap"}><div className={"heading-menu-box"}><a href={"#"} className={"header-menu-link w-inline-block"}><img loading={"lazy"} src="/assets/6a5e950d52478c467739fde1_Frame.png" alt={"Blue plus sign icon on transparent background."} className={"heading-menu-img"} /><div className={"heading-text"}>Menu</div></a></div><div className={"header-menu-wrap"}><div className={"header-menu-item-wrapper"}><div className={"header-menu-img-wrap"}><a href={"/"} aria-current={"page"} className={"header-logo-link w-nav-brand w--current"}><Wordmark /></a></div><div className={"header-menu-text-wrap"}><div className={"heading-menu-item-wrap"}><a href={"/"} aria-current={"page"} className={"menu-link w--current"}>Hero</a></div><div className={"heading-menu-item-wrap"}><a href={"#about"} className={"menu-link"}>About</a></div><div className={"heading-menu-item-wrap"}><a href={"#service"} className={"menu-link"}>Services</a></div><div className={"heading-menu-item-wrap"}><a href={"#project"} className={"menu-link"}>Project</a></div><div className={"heading-menu-item-wrap"}><a href={"#team"} className={"menu-link"}>Team</a></div><div className={"heading-menu-item-wrap"}><a href={"#testimonial"} className={"menu-link"}>Testimonials</a></div><div className={"heading-menu-item-wrap"}><a href={"#Comment"} className={"menu-link"}>Contact</a></div></div></div></div></div><div className={"heading-right-content-wrap"}><a href={"#contact"} className={"od-cta"} aria-label={"Book a free 30-minute strategy call"}><span className={"od-cta-roll"}><span>Book a call</span><span aria-hidden={true}>Book a call</span></span><span className={"od-cta-mark"} aria-hidden={true}>→</span></a></div></div></div></section>
    </>
  );
}
